### PR TITLE
PR to send to code review

### PR DESCRIPTION
**Pull request by camfilho**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
## Nice Job @camfilho 👋👋
Your project output looks great, however, let us add these few suggestions to make our project 👌
* [x] let us resolve the horizontal scroll that is on our page
Screenshot from 2019-10-15 16-18-49
> this can occur in a project when a ```row```  is conflicting with ```.container``` 
> generally it could also occur when a given width is set in ```pixel``` whilst it should have been stated in ```%```
* [x] let us fix navbar behavior at xs 🙂
> at xs the original Newsweek app only display only one fixed navbar 
Screenshot from 2019-10-15 16-34-36
Screenshot from 2019-10-15 16-34-45

* [x] let us fix the behavior of our footer at xs. Compare the original to what we have currently🙂

Screenshot from 2019-10-15 16-36-57
Screenshot from 2019-10-15 16-37-15

* [x] fix the **[warnings]** returned by the[ validator ](https://validator.w3.org)after uploading the index file.🙂

* [x] readme🙂
readme file is supposed to be descriptive enough(refer [to](https://github.com/Forison/smashing-magazine/blob/master/README.md) ). currently, your readme is too brief🙂

## Kindly make these changes and submit for review😇
feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.

#### Happy coding😇😇😇

**Comment by camfilho** [comment]
@Forison thanks!
Applied the changes and sent to code review again.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good job @camfilho 👏
You have successfully implemented the changes I suggested 
### Go ahead and merge to master
# your project is approved💪 
Happy coding😇😇😇

**Pull request merged**
